/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eelections;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

/**
 *
 * @author karalis
 */
public class mainMenu extends javax.swing.JFrame {

    /**
     * Creates new form mainMenu
     */
    public mainMenu() {
        
        try {
            
            // Προετοιμασία των συστατικών της φόρμας
            initComponents();
            // Κεντράρουμε την φόρμα
            this.setLocationRelativeTo(null);
            this.setTitle("ΗΛΕΚΤΡΟΝΙΚΗ ΨΗΦΟΦΟΡΙΑ");
            this.setMaximumSize(this.getSize());
            this.setMinimumSize(this.getSize());

            // Προσθέτουμε ενα WindowListener για να ελέγχουμε την έξοδο
            this.addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosing(WindowEvent e) {
                    confirmClose();
                }
            });
        }  catch (Exception ex){
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Πρόβλημα...", 
                                              JOptionPane.ERROR_MESSAGE);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        handlingCandidates = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        handlingCandidates.setText("ΔΙΑΧΕΙΡΙΣΗ ΥΠΟΨΗΦΙΩΝ");
        handlingCandidates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                handlingCandidatesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(handlingCandidates, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(handlingCandidates)
                .addContainerGap(257, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmClose() {
         // Δημιουργούμε μια φόρμα αφού showInternalConfirmDialog ζητάει
         // parent φόρμα που να έχει parent φορμα και αυτό δεν συμβαίνει
         // με την FormMain
         JInternalFrame jTemp = new JInternalFrame();
         jPanel1.add(jTemp);
         
         // Κεντράρισμα της φόρμας
        Dimension desktopSize = this.getSize();
        Dimension jInternalFrameSize = jTemp.getSize();
        int width = (desktopSize.width - jInternalFrameSize.width) / 2;
        int height = (desktopSize.height - jInternalFrameSize.height) / 2;
        jTemp.setLocation(width, height);
         
        if (JOptionPane.showInternalConfirmDialog(jTemp, "Θέλετε να κλείσετε την εφαρμογή;", 
                                          "Έξοδος", JOptionPane.OK_CANCEL_OPTION,
                                          JOptionPane.QUESTION_MESSAGE) == JOptionPane.OK_OPTION) {
            System.exit(0);
        } else {
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            jPanel1.remove(jTemp);
        }
    }
    private void handlingCandidatesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_handlingCandidatesActionPerformed
        // TODO add your handling code here:
            diaxYpopsifion dYFrame = new diaxYpopsifion();
            dYFrame.setVisible(true);
                
    }//GEN-LAST:event_handlingCandidatesActionPerformed

                
     public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {
        /* Create and display the form */
            public void run() {
                mainMenu menuFirst = new mainMenu();
                menuFirst.setVisible(true);
                try {
                    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                        if ("Nimbus".equals(info.getName())) {
                            javax.swing.UIManager.setLookAndFeel(info.getClassName());
                            break;
                        }
                    }
                } catch (ClassNotFoundException ex) {
                    java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                    java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }

                JButton electionSimulation = new JButton("ΠΡΟΣΟΜΟΙΩΣΗ ΕΚΛΟΓΩΝ");
                electionSimulation.setMnemonic(KeyEvent.VK_B);
                menuFirst.add(electionSimulation);
                                                
            }    
        });            
     }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton handlingCandidates;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
   
 
}
